### ISSUE TITLE
SettingFlyout.Background issue

### ISSUE THREAD

**Issue by jcamachov** [timheuer/callisto#113] opened 2012-10-30 09:34 UTC
I just update Callisto last release to my Proyect. In this project (vb.net) I have a SettingsFlyout with Colors.DarkOrange  in background. When I update to last release the background is always white, it seems that background color that I pass in code doesn't work.

Is a bug?, or I must change any part of my code... 

The code that I use is this:

Dim settings As New SettingsFlyout()
settings.FlyoutWidth =SettingsFlyout.SettingsFlyoutWidth.Wide
settings.HeaderText = loader.GetString("cmdConfigTitle")
settings.Background = New SolidColorBrush(Colors.DarkOrange)

Thank you in advance!

**Comment by timheuer** [comment] 2012-10-30 14:56
This is a dupe of #81 -- set ContentBackgroundBrush

**Closed as completed** 2012-10-30 14:56 UTC
Labels: duplicate
