### ISSUE TITLE
Cascading menu

### ISSUE THREAD

**Issue by RobertHF** [timheuer/callisto#149] opened 2013-01-02 11:57 UTC
I'm thinking about building on the menu to create a single-level cascading menu. That is, a menu item would have a little graphic arrow, and when pressed would display a submenu. When the submenu item was selected, both the sub menu and the parent menu would be dismissed.

Are there any potential pitfalls in attempting this? Are cascading menus acceptable in the UI?

**Comment by timheuer** [comment] 2013-01-02 15:22
Cascading/sub-menus like that aren't really a part of the Windows design language.  "acceptable" becomes a relative term.  However you won't see these much (if at all) in Microsoft apps.  

(since this is more of a question and not a bug, closing as non-bug)

**Closed as completed by timheuer** 2013-01-02 15:22 UTC
Labels: wontfix
