### ISSUE TITLE
When a Menu is wrapped in a UserControl which is added to a Flyout, the app crashes when hitting Escape

### ISSUE THREAD

**Issue by areijngoudt** [timheuer/callisto#166] opened 2013-02-20 11:58 UTC
The Menu.OnKeyDown expects the parent to be a Flyout:
private void OnKeyDown(object sender, KeyRoutedEventArgs args)
        {
            switch (args.Key)
            {
                case Windows.System.VirtualKey.Escape:
                    ((Flyout)this.Parent).IsOpen = false;
                    break;
When the Menu is wrapped in a UserControl, the Cast fails when [Escape] is pressed, and the app is terminated

**Comment by stefanolson** [comment] 2013-03-01 23:39
Duplicate of: https://github.com/timheuer/callisto/issues/140

**Closed as completed** 2013-03-02 00:40 UTC
Labels: duplicate
