### ISSUE TITLE
CUSTOM DIALOG

### ISSUE THREAD

**Issue by GIORGIOSF** [timheuer/callisto#208] opened 2013-06-03 13:00 UTC
CustomDialog is supposed to enhance MessageDialog; however - if I understand well - it lacks some fundamental features:
- because MessageDialog is  invoked with await ... ShowAsync it is modal, whereas CustomDialog is not;
- by means of the associated CommandInvokedHandler, MessageDialog informs the caller program of which button has been clicked by the user;
- 'Esc' dismisses MessageDialog with a default response.

Is there any way to obtain similar behavior with CustomDialog?
This would be instrumental e.g. to implement an 'Enter passord' dialog.

**Comment by timheuer** [comment] 2013-06-04 02:14
Duplicate of #207

**Closed as completed by timheuer** 2013-06-04 02:14 UTC
Labels: duplicate
