### ISSUE TITLE
DateTimePicker control

### ISSUE THREAD

**Issue by Porkolito** [timheuer/callisto#37] opened 2012-06-01 09:28 UTC
I dont know but I can't use in DatePicker. I installed your package, I wrote Using Callisto.Controls but DatePicker is not there.

**Comment by timheuer** [comment] 2012-06-01 13:59
Date pickets not implemented yet

-th

**Comment by timheuer** [comment] 2012-06-01 15:15
Duplicate of #3

**Closed as completed by timheuer** 2012-06-01 15:15 UTC
Labels: duplicate
