### ISSUE TITLE
SettingsFlyout doesn't work appropriately with input boxes and a touch screen

### ISSUE THREAD

**Issue by csmaster2005** [timheuer/callisto#92] opened 2012-09-27 08:37 UTC
If I have an input box in a SettingsFlyout, and tap the screen, the keyboard comes up and scrolls the text box out of view.

This is for a non-rooted flyout. I've also tried rooting the flyout HostPopup, but it does not seem to fly in correctly from the right edge.

**Comment by timheuer** [comment] 2012-09-27 14:47
This is a duplicate of #85 which has recently been fixed.  A version with this fix isn't yet released though.

**Closed as completed by timheuer** 2012-09-27 14:47 UTC
Labels: duplicate

**Comment by csmaster2005** [comment] 2012-09-27 17:21
Thanks. I saw #85 but didn't realize that it wasn't published (I grabbed newest bits and it didnt fix it when I tried). Any ETA for when the fix will be released?

**Comment by timheuer** [comment] 2012-09-27 17:29
I assume when you say "gabbed newest bits" you mean the VSIX or NuGet
package.  I hope to push it out this week.

---

http://timheuer.com/blog/
twitter: @timheuer

**Comment by csmaster2005** [comment] 2012-09-27 17:54
No, I had downloaded the master repository as a zip, and pulled it into my project.

**Comment by csmaster2005** [comment] 2012-09-27 18:07
Sorry I am mistaken - I grabbed your project and tested it with the sample, and it worked. I then retried it in mine, and it now works. I must of not 'really' recompiled the callisto dll, and it was using the old one. Thanks, glad it's working now!
