### ISSUE TITLE
Left/Right placements of Flyout aren't positioning correctly on secondary screen

### ISSUE THREAD

**Issue by endquote** [timheuer/callisto#200] opened 2013-05-17 00:01 UTC
In the sample app, if you set the flyout menu position to left or right, and if your app is on a secondary screen, the flyout ends up at the top of the screen. In my case, the window argument to PlacePopup is: -1920,520,1920,1080

**Comment by timheuer** [comment] 2013-05-17 00:26
Dupe of #109

**Closed as completed by timheuer** 2013-05-17 00:26 UTC
Labels: duplicate
