### ISSUE TITLE
Cannot change indicator colours in FlipViewIndicator

### ISSUE THREAD

**Issue by pcolmer** [timheuer/callisto#121] opened 2012-11-20 14:39 UTC
In the app I'm writing, the selected image is shown with a black rectangle and the other image indicators are grey rectangles. I'm somewhat assuming that these colours are coming through from the derived ListView somewhere but although properties like Foreground are exposed, the only one that seems to do anything is Background, and that doesn't help.

Is there a way of changing the colours used by the indicators and, if not, can this be provided please?

Thanks.

Philip

**Comment by timheuer** [comment] 2013-03-28 16:16
Duplicate of #150

**Closed as completed by timheuer** 2013-03-28 16:16 UTC
Labels: duplicate
