### ISSUE TITLE
Handling Sub menus with SettingsFlyout

### ISSUE THREAD

**Issue by realworld666** [timheuer/callisto#98] opened 2012-10-06 18:58 UTC
Is there functionality to support sub menus with SettingsFlyout? I can open a new SettingsFlyout but the back button always takes me back to the main settings screen.

**Comment by timheuer** [comment] 2012-10-06 21:03
This is a dupe of #47 where I need to expose a better way of controlling the 'back' behavior.

**Closed as completed by timheuer** 2012-10-06 21:03 UTC
Labels: duplicate
